name: CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master"]

env:
  PYTHON_VERSION: "3.11"

jobs:
  check-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7.5.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Format check
        run: uvx ruff format --check .
      - name: Lint
        run: uvx ruff check .
      - name: Type check
        run: uvx --with . pyright .
